apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  {{ if .annotations }}
  annotations:
    {{ range $key, $value := .annotations }}
    {{ $key }}: "{{ $value }}"
    {{ end }}
  {{ end }}
  {{ if .labels }}
  labels:
    {{ range $key, $value := .labels }}
    {{ $key }}: {{ $value }}
    {{ end }}
  {{ end }}
