# The configuration file is loaded by the test suite
#
# Each configuration parameter can be overridden by a command line
# option. For instance:
# buildImages => --build-images
# requirements.must => --requirements-must

# whether to build and publish images before running tests.
buildImages: false

# image repository.
# e.g. docker.io/user
# when ko, use $KO_DOCKER_REPO environment variable
imageRepository: ko

requirements:
  must: true
  may: true
  should: true

components:
  eventing:
    sources:
      github:
        require: main # from source.

  serving:
    require: 0.17

  networking:
    name: istio
    require: 0.17

  event.observer:
    target: log
